events {}

http {

    server {
        listen 80;

        # Backend API
        location /api/ {
            proxy_pass http://backend:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Transactions service
        location /transactions/ {
            proxy_pass http://transactions:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Frontend UI
        location / {
            proxy_pass http://studentportfolio:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

}